---
- name: Deploy WordPress with LAMP stack
  hosts: webservers
  become: yes
  become_method: sudo
  gather_facts: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-apt
          - acl
          - sudo
        state: present

  roles:
    - prepare_docker
    - prepare_db_server
    - prepare_http_server
    - prepare_php
    - prepare_wordpress

  post_tasks:
    - name: Check if Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
      register: apache_running

    - name: Display WordPress installation information
      debug:
        msg: |
          WordPress has been successfully installed!
          
          You can access your WordPress site at: http://{{ ansible_host }}
          
          Database Information:
          - Database Name: {{ mariadb_database | default('wordpress') }}
          - Database User: {{ mariadb_user | default('wordpress') }}
          - Database Host: {{ mariadb_container_name | default('localhost') }}
          
          WordPress Admin:
          - Username: {{ wordpress_admin_user | default('admin') }}
          - Email: {{ wordpress_admin_email | default('admin@example.com') }}
          
          Please remember to change all default passwords!
      when: apache_running is success
